### ISSUE TITLE
cannot edit question answer in frontend and admin

### ISSUE THREAD

**Issue by vxsx** [aldryn/aldryn-faq#105]
ckeditor doesn't load sometimes. it is inconsistent, but I can reproduce on local most of the time

this is the view source of the page when ckeditor doesn't work
![screen shot 2015-07-20 at 14 13 54](https://cloud.githubusercontent.com/assets/366813/8779981/8ac7bfa4-2f06-11e5-94c0-02027604cf9a.png)

this is the same page after few cmd+shift+R
![screen shot 2015-07-20 at 14 14 36](https://cloud.githubusercontent.com/assets/366813/8779991/96958ac8-2f06-11e5-9eb7-280afe7af815.png)

and even when the ckeditor loads - it has this problem, not sure if it's a separate issue
![screen shot 2015-07-20 at 13 54 29](https://cloud.githubusercontent.com/assets/366813/8780031/c4a24064-2f06-11e5-9e71-55dfdaef4549.png)

**Comment by vxsx** [comment]
the empty cms plugins dropdown also happens on aldryn-newsblog btw

**Comment by mkoistinen** [comment]
This appears to be an issue with admin-sortable2: http://cl.ly/3a2v3k1O333E

**Comment by mkoistinen** [comment]
OK, there was a bug in DAS2 that was causing this. I've submitted a PR for it here: https://github.com/jrief/django-admin-sortable2/pull/71, perhaps someone can review that?

**Comment by mkoistinen** [comment]
OK, https://github.com/jrief/django-admin-sortable2/pull/71 was merged, but there's not been a new release yet. Should we make a release that pulls from DAS2::master?

**Comment by mkoistinen** [comment]
This has been fixed in new versions of Admin Sortable 2. v0.5.2.
