### ISSUE TITLE
Missing Django 1.7 migration with aldryn-faq==1.0.8

### ISSUE THREAD

**Issue by trawick** [aldryn/aldryn-faq#146]
Migration 0009 is needed with Django==1.7.10 and Python 3.4:

```
$ python manage.py makemigrations --dry-run
Migrations for 'aldryn_faq':
  0009_auto_20151116_0035.py:
    - Alter field app_data on faqconfig
```

My environment:

Python 3.4.3, Django 1.7.10,

```
aldryn-apphooks-config==0.2.6
aldryn-boilerplates==0.7.3
aldryn-common==1.0.0
aldryn-faq==1.0.8
aldryn-reversion==1.0.3
aldryn-search==0.2.10
aldryn-translation-tools==0.2.1
Django==1.7.10
django-admin-sortable2==0.6.2
django-admin-sortable==2.0.7
django-appconf==1.0.1
django-appdata==0.1.5
django-classy-tags==0.7.0
django-cms==3.2.0
djangocms-admin-style==1.0.7
djangocms-text-ckeditor==2.8.0
django-formtools==1.0
django-haystack==2.4.1
django-parler==1.5.1
django-reversion==1.8.7
django-sekizai==0.9.0
django-sortedm2m==1.1.1
django-spurl==0.6.2
django-standard-form==1.1.1
django-taggit==0.17.6
django-treebeard==3.0
html5lib==0.9999999
lxml==3.5.0
Pillow==3.0.0
python-slugify==1.1.4
six==1.10.0
Unidecode==0.04.18
URLObject==2.4.0
YURL==0.13
```

With the same modules installed and Python 2.7, the issue does not occur.

**Comment by trawick** [comment]
Description just updated with somewhat-simplified config and observation about Python 2.7.

**Comment by trawick** [comment]
I think the issue is [here in the initial migration](https://github.com/aldryn/aldryn-faq/blob/master/aldryn_faq/migrations/0001_initial.py#L64).  Your Django 1.7.x with Python 2 has spit out ``default=b'{}'`` when generating the migration but ``b'{}'`` is not the same as ``'{}'`` in Python 3, and Django 1.7.10 with Python 3 wants to generate a migration to fix it.

If I hide the migrations directory and rebuild migrations, Django 1.7.10 with Python 3.4 spits out

```
migrations.CreateModel(
            name='FaqConfig',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, auto_created=True, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='type')),
                ('namespace', models.CharField(default=None, unique=True, max_length=100, verbose_name='instance namespace')),
                ('app_data', app_data.fields.AppDataField(editable=False, default='{}')),
                ...
```

(default for ``app_data`` isn't a byte string)

Python 2.7.6 and the same Django (1.7.10), with the original aldryn-faq migrations directory hidden, builds this:

```
        migrations.CreateModel(
            name='FaqConfig',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('type', models.CharField(max_length=100, verbose_name='type')),
                ('namespace', models.CharField(default=None, unique=True, max_length=100, verbose_name='instance namespace')),
                ('app_data', app_data.fields.AppDataField(default=b'{}', editable=False)),
```

Yuck!

At any rate, ``default='{}'`` would work the same for Python 2 and Python 3.  (Python 2 doesn't think a migration is needed in that case.)  I **guess** adding the additional migration that Python 3.4+Django 1.7.10 doesn't hurt anyone.

**Comment by czpython** [comment]
Fixed by https://github.com/aldryn/aldryn-faq/pull/153
