### ISSUE TITLE
has no attribute get_query_set in django-taggit

### ISSUE THREAD

**Issue by stefanfoulis** [aldryn/aldryn-faq#180]
Newer versions of django-taggit have dropped the backwards compatibility shim for ``get_query_set``, the Django 1.6 way of naming that method on the manager. This should now be called ``get_queryset``.

It is used here:
https://github.com/aldryn/aldryn-faq/blob/ec1e89f9f7b650fd547a01882ca2c8e0b62a9af6/aldryn_faq/admin.py#L80

And maybe in other places.

With this bug, it is currently not possible to add a question.

**Comment by Pyc0kw4k** [comment]
Thank you !
