### ISSUE TITLE
No module named "parler"

### ISSUE THREAD

**Issue by dossan** [aldryn/aldryn-faq#29]
I am trying to install this plug-in, but now I have a problem running the command to migrate the plug-in, it says:

    raise ImproperlyConfigured('ImportError %s: %s' % (app, e.args[0]))
    django.core.exceptions.ImproperlyConfigured: ImportError parler: No module named 'parler'

I have already added the string 'parler' to the INSTALLED_APPS, so I suppose it's because the module is not found or does not exist.

**Comment by mkoistinen** [comment]
@dossan please do a `pip install django-parler`, I'll fix setup.py, which still references the old library, django-hvad.

**Comment by mkoistinen** [comment]
Fixed in PyPI release 0.10.4
