### ISSUE TITLE
Application labels aren't unique

### ISSUE THREAD

**Issue by dossan** [aldryn/aldryn-faq#30]
I have tried to installed again this plug-in with `pip` and I have another error:

     "duplicates: %s" % app_config.label)
    django.core.exceptions.ImproperlyConfigured: 
    Application labels aren't unique, duplicates: djangocms_text_ckedito

**Comment by mkoistinen** [comment]
Can anyone repeat this?

**Comment by mkoistinen** [comment]
Closing
