### ISSUE TITLE
Add 'current_app' to 'reverse()' calls.

### ISSUE THREAD

**Issue by mikek** [aldryn/aldryn-faq#41]
I am having troubles calling `{{ question.get_absolute_url }}` in templates. Correction: this happens in custom template tag template, that is not on the view with `AppConfigMixin`.

Here is a possible fix, as I can see it. @mkoistinen , can you, please, modify Question model `get_absolute_url()` to include `current_app=self.category.appconfig.namespace` in the `reverse` calls? (And probably similar adjustments for other model(s).)

**Comment by vtay** [comment]
@mkoistinen - is there any update on this since we discussed?
