### ISSUE TITLE
View at the root of app urlconf

### ISSUE THREAD

**Issue by mikek** [aldryn/aldryn-faq#42]
Please, consider adding view at the root of app urlconf that will show all categories in a nested list. Without such a view, if we attach faq application to a Django CMS page, that page itself get's parent template and is not handled by the application.

Something like 
```python
url(r'^$', FaqCategoriesListView.as_view(), name='faq-categories'),
```
would be awesome.

**Comment by mkoistinen** [comment]
Duplicate of #28
