### ISSUE TITLE
NoReverseMatch at /en/admin/aldryn_faq/question/sort/

### ISSUE THREAD

**Issue by Chive** [aldryn/aldryn-faq#9]
**NoReverseMatch at /en/admin/aldryn_faq/question/sort/**
Reverse for 'admin_do_sorting' with arguments '('',)' and keyword arguments '{}' not found.

Happens when clicking on `Change order` at /admin/aldryn_faq/question/

Traceback:
https://dpaste.de/cV0Y

**Comment by mkoistinen** [comment]
@Chive Would it be possible for you to re-test with latest version? I've fixed a number of issues while adding test coverage and converting to parler.

**Comment by mkoistinen** [comment]
Closed.
